version: "3"
services:
  tcp-server:
    build: ./tcp-server
    command: python3 -u ./tcp-server/server.py
    ports:
      - "3737:3737"
    volumes:
      - .:/aefdemo
    links:
      - flask-add
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - flask-add
  flask-add:
    build: ./flask-adding
    command: python3 -u ./flask-adding/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/aefdemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
