version: "3"
services:
  tcp-server:
    build: ./tcp-server
    command: python3 -u ./tcp-server/server.py
    ports:
      - "3737:3737"
    volumes:
      - .:/aefdemo
    links:
      - flask-add
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - flask-add
  database:
      image: mongo:3.0.2
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "10"
    mongo-express:
      image: mongo-express
      environment:
          - ME_CONFIG_MONGODB_SERVER=database
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
          - ME_CONFIG_MONGODB_AUTH_DATABASE=buyqaw
          - ME_CONFIG_BASICAUTH_USERNAME=root
          - ME_CONFIG_BASICAUTH_PASSWORD=1234
      ports:
        - "8081:8081"
      links:
        - database
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "10"
      depends_on:
        - database